### ISSUE TITLE
Mapsforge lines not rendered correctly at large zooms

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#109]
how to reproduce the issue:

Used mapsforge map: http://ftp5.gwdg.de/pub/misc/openstreetmap/openandromaps/maps/Germany/sachsen.zip

Used render theme:
default.xml, with one modification:

added:

``` xml
        <m k="contour_ext" zoom-min="10">
            <m v="elevation_major">
                <line stroke="#8E8072" width="1.3" />
            </m>
        </m>
```

right after 

``` xml
<m e="way">
```

to enable rendering of elevation lines.

Enable GridLayer for easier navigation.
Go to Grid 16/35226/21988
The line that makes a sharp 'turn' to the left should connect to the line straight above it.

Panning the map around there are many wrong rendered lines visible.

Image attached
![screenshot_20160807-191342](https://cloud.githubusercontent.com/assets/1132106/17466029/99b062b8-5cd3-11e6-9ada-0ce57c0f572e.png)

**Comment by stleusc** [comment]
Rendering the same map file in Locus does not present that issue, so I assume it is VTM and not the map

**Comment by stleusc** [comment]
Also ran the same example in latest mapsforge android demo... looks correct (of course I had to adjust the theme to get it rendered).

**Comment by devemux86** [comment]
- Mapsforge uses software rendering
- AFAIK Locus uses a modified Mapsforge version
- VTM uses OpenGL for rendering

I remember reading a similar case in OpenScienceMap repository, see https://github.com/opensciencemap/vtm/issues/122
Are you sure that this problem appears now after latest commits, previously it worked correctly?

**Comment by devemux86** [comment]
I checked before yesterday's commits and this issue appears there too.
So it's not something new with Mapsforge maps rendering.

There are two things to consider here:
- VTM uses older Mapsforge code for parsing its maps (we could update it)
- OpenGL is different and more strict than software rendering in such cases

**Comment by stleusc** [comment]
Sorry if I implied in any way that this issue was due to a recent change.
My app uses a rather old version of original VTM. I noticed the issue there. But of course no sense of reporting it if it was fixed already, so I tried your latest version and a few other tools for reference. This is not new....

But I have a few ideas...
a) old issue opensciencsemap#122 occured exactly on tile edges and artifacts changed with zoom, this is not 100% the same... right now the artifact is the same across all zoom levels.
b) contour lines were never visible, so I'm thinking this could be something since day 1
c) it almost looks like reading map data so updating the parser would be a good start I think.

Anything I can be of help? Not an OpenGL expert at all though ;-)

**Comment by devemux86** [comment]
>a) old issue opensciencsemap#122 occured exactly on tile edges and artifacts changed with zoom, this is not 100% the same... right now the artifact is the same across all zoom levels.

Note that Mapsforge maps work with sub files based on zoom intervals. Details for all these exist in our docs for [map file format](https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md) and [map writer](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md).
Last zoom interval starts at 12 with base zoom 14, where data is retrieved. So you can still see the problem at zoom 12 coming from the 14 tiles grid.

The issue exists also in some lake polygons that are split among 4 adjacent tiles, so it's not only on contour lines (or they're contour polygons?).

If this is due to old Mapsforge parsing, then the answer could be in VTM [MapDatabase](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java) class comparing with corresponding Mapsforge [MapFile](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MapFile.java) class.

**Comment by stleusc** [comment]
yes, I would say it stays the same below zoom 12...

**Comment by devemux86** [comment]
@stleusc could check again your case after the `TileClipper` buffer increase in #231?
