### ISSUE TITLE
Marker clustering

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#312]
Implement clustering in adjacent markers.

**Comment by devemux86** [comment]
See PR #296 and #310 by @nebular.

**Comment by devemux86** [comment]
Closing for now.
The implementation can use some improvements regarding the clusters calculation and their rendering.

**Comment by deviousgeek** [comment]
Is this on the current snapshot on sonatype? Looks like it has been updated recently but I could not import the new classes.

**Comment by devemux86** [comment]
Should be in latest snapshots and I see they were built successfully.

Perhaps you need to somehow force Gradle to update them "now" in your build?
e.g. see a way in [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots)

**Comment by deviousgeek** [comment]
Thanks! Ended up pulling it to make a few changes anyway.

**Comment by devemux86** [comment]
> Ended up pulling it to make a few changes anyway.

Any improvement is welcome! :slightly_smiling_face:

**Comment by nebular** [comment]
If I can be of any help please don't hesitate to ask :)

**Comment by deviousgeek** [comment]
I might do, it's very might spaghetti code at the moment. The only big issue I am having right now is the overlapping of clusters. It's a bit confusing when clusters end up on top of each other, and I am trying to avoid this by increasing the grid size (to limited success). I'm going to persevere and see what I end up with. ;)

**Comment by nebular** [comment]
The reason why that happens is that the "cluster" is really the first element with its bitmap changed, so if there's a succession of markers, the latest ones will not be clustered together until they "invade" the first item position. 

- The good thing of this approach is that it's very quick to do the calculations and the required changes to the `MarkerRender` are minimal. 

- The bad thing is that, I agree, you get more overlapping than it is desirable. 

What would solve the situation is, when one item act as a cluster, to update its position to the middle point. Probably a good approach would be to store the new calculated coordinates in new properties in`InternalItem.Clustered` and, if the item acts as a cluster, use those coordinates instead of the original ones.

Incrementing the GRIDSIZE as you have experienced, kind of hides the problem, but depending on how the markers are spaced it can happen again. This week I'm busy with a project deadline, the next one (if you don't fix it before) I will gladly try to improve the algorythm.

**Comment by deviousgeek** [comment]
Very interesting, thanks for the info!

**Comment by devemux86** [comment]
What seems a bit strange, from user's perspective, is that during zoom in / out the clusters are created in non deterministic way, like each time a random clustering happens.
