### ISSUE TITLE
PathLayer overlay touch events

### ISSUE THREAD

**Issue by mathieudebrito** [mapsforge/vtm#316]
Hi guys !
It would be great to implement a way to listen to onSingleTap events on PathLayers :)
Cheers

**Comment by luis901101** [comment]
`
/**
 * Created by luis on 8/6/17.
 */

public final class MyRoutesLayer extends MyLayer implements GestureListener
{
    public static final int ROUTE_LAYER_INDEX = 3;
    private MapView map_view;
    private List<MyPathLayer> route_layers;
    private MyPathLayer.OnPathLayerClickListener onPathLayerClickListener;

    public MyRoutesLayer(MapView map_view)
    {
        super(map_view);
        this.map_view = map_view;
        route_layers = new ArrayList();
    }

    public void setOnPathLayerClickListener(MyPathLayer.OnPathLayerClickListener onPathLayerClickListener)
    {
        this.onPathLayerClickListener = onPathLayerClickListener;
    }

    public void add(MyPathLayer route_layer)
    {
        route_layers.add(route_layer);
    }

    public int size()
    {
        return route_layers.size();
    }

    public void showRoutes(boolean show)
    {
        for(MyPathLayer route : route_layers)
        {
            if(show && !route.isEnabled())
                route.setEnabled(true);
            else
                if(!show && route.isEnabled())
                    route.setEnabled(false);
        }
    }

    public void clearRoutes()
    {
        if(!isEmpty())
        {
            for(MyPathLayer route : route_layers)
                map_view.removeLayer(route);
            route_layers.clear();
            map_view.update();
        }
    }

    public boolean isEmpty()
    {
        return size() == 0;
    }

    public MyPathLayer get(int i)
    {
        return route_layers.get(i);
    }

    public List<MyPathLayer> getAll()
    {
        return route_layers;
    }

    @Override
    public void setEnabled(boolean enabled)
    {
        for(MyPathLayer path_layer : route_layers)
            path_layer.setEnabled(false);
        super.setEnabled(enabled);
    }

    public void selectAsMainRoute(MyPathLayer main_path_layer)
    {
        main_path_layer.showAsAlternative(false);
        for(int i = 0; i < size(); i++)
        {
            MyPathLayer path_layer = get(i);
            if(path_layer.getId() != main_path_layer.getId())
                path_layer.showAsAlternative(true);
            else
                route_layers.remove(i--);
        }

        route_layers.add(0, main_path_layer);
        map_view.removeLayer(main_path_layer.getLayerIndex());

        for(int i = ROUTE_LAYER_INDEX; i < map().layers().size(); i++)
        {
            Layer layer = map().layers().get(i);
            if(!(layer instanceof MyPathLayer) && !(layer instanceof MyRoutesLayer))
            {
                map_view.addLayer(i, main_path_layer);
                return;
            }
        }

    }

    @Override
    public boolean onGesture(Gesture gesture, MotionEvent motionEvent)
    {
        if(gesture instanceof Gesture.Tap)
        {
            if(size() > 0)
            {
                ViewController mapPosition = map_view.map().viewport();
                Box box = mapPosition.getBBox(null, 128);
                box.map2mercator();
                box.scale(1000000.0D);

                Point touch_point = new Point(motionEvent.getX() - mMap.getWidth() / 2, motionEvent.getY() - mMap.getHeight() / 2);

                for(MyPathLayer path_layer : route_layers)
                {
		    double stroke_width = path_layer.getStyle().strokeWidth * 2;
                    for(int i = 0; i < path_layer.getPoints().size(); ++i)
                    {
                        GeoPoint point = path_layer.getPoints().get(i);
                        if(box.contains((double) point.longitudeE6, (double) point.latitudeE6))
                        {
                            for(int j = i; j < path_layer.getPoints().size() - 1; j++)
                            {
                                GeoPoint gp1 = path_layer.getPoints().get(j);
                                GeoPoint gp2 = path_layer.getPoints().get(j+1);

                                Point p1 = new Point(), p2 = new Point();
                                mapPosition.toScreenPoint(gp1, p1);
                                mapPosition.toScreenPoint(gp2, p2);

                                double distance = new MathUtils.Segment(p1, p2).distanceToPoint(touch_point);

                                if(distance <= stroke_width)
                                {
                                    if(size() > 1)
                                        selectAsMainRoute(path_layer);
                                    if(onPathLayerClickListener != null)
                                    {
                                        onPathLayerClickListener.onPathLayerClick(path_layer);
                                        return true;
                                    }
                                    return false;
                                }
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
}`

This class works very similar to ItemizedLayer, it implements GestureListener and in the onGesture checks for a TAP gesture. Once a TAP gesture is checked then a Box is used to check if there is any point from path's points inside the visible map screen, if there is any then from that exact point to the end of the path's points it checks the distance from the tap screen point to the segment that is created every two consecutive path's points, if that distance is less or equal than the (stroke width x 2) of the path's style then an onPathLayerClick event is triggered. The selectAsMainRoute method is used only for visual purposes.

Note: This class is part of a bigger project that's why the MyLayer, MyPathLayer, MyRoutesLayer, etc..., but that classes has only minimal customizations specific of the project. The MathUtils.Segment is a custom implementation for estimate the distance from a point to a segment using basic maths.

I Hope it works... For me works like a charm.

**Comment by mathieudebrito** [comment]
Ok, Thank you very much, I will give it a try asap :)
Really, thank you !

**Comment by devemux86** [comment]
Thanks @luis901101 !
We could include it in VTM, enhancing both `PathLayer`(s) API.

Would need to review the implementation for improved performance, e.g. point to point distance seems adequate enough(?).

**Comment by luis901101** [comment]
I opted for the distance from a point to a segment in order to solve this problem but I think the performance could be improved by looking more into the specifications of this problem and take another approach, or the same approach but changing some things like work with coordinates instead of screen points or use a fast search algorithm, etc. I have made some changes to my algorithm in order to make it more reliable, not faster, I mean when there are some routes (main route and alternatives) too close each other the algorithm should select the closest one to the touch screen point, not select the first that is on range...
I am glad to help with anything I can.

**Comment by devemux86** [comment]
Implementation doesn't perform any view bounds check, since can have a line with points outside view and still should be able to touch it. Will see if can improve further the algorithm.

**Comment by devemux86** [comment]
Examples can be seen in [PathOverlayActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/PathOverlayActivity.java) and [PathLayerTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/PathLayerTest.java).
(set `ANIMATION=false` to test)

**Comment by mathieudebrito** [comment]
Awesome ! Thx very much
