### ISSUE TITLE
Extrusions default height

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#409]
Include default height option for extrusions in render themes and use it in building layer.

**Comment by devemux86** [comment]
@mathieudebrito there is now a more formal way to control buildings default height via render themes, like their other attributes (deprecated the #351 method).

**Comment by mathieudebrito** [comment]
Awesome ! I will definitely have a look at it !

Le 26 sept. 2017 18:23, "Emux" <notifications@github.com> a écrit :

@mathieudebrito <https://github.com/mathieudebrito> there is now a more
formal way to control buildings default height via render themes, like
their other attributes (deprecated the #351
<https://github.com/mapsforge/vtm/pull/351> method).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mapsforge/vtm/issues/409#issuecomment-332254754>, or mute
the thread
