### ISSUE TITLE
Reference element tag values in style rules

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#427]
Currently there is now way to reference element tag values in style rules. Element name is an example of such reference but the way it is implemented in VTM is kind of hack - separate layer and hooks is required for that.

Good example of practical importance of such feature would be possibility to supply priority and font size for labels or color and fade level for lines in map data.

I've looked at renderer source code and didn't see any good way to implement this. I do not want to screw the hole library so may be someone has ideas how to implement this?

@hjanetzek ?

**Comment by devemux86** [comment]
(not sure if understand correctly the description)

Vector data should provide what their purpose is - only the data - not how the data should be rendered, i.e. fonts, colors, etc.
Render themes are those which should control the map rendering with fonts, colors, etc.

Per Mapzen [description](https://mapzen.com/documentation/vector-tiles/):
_"Vector tiles are square-shaped collections of geographic data that contain the map feature geometry, such as lines and points. Information about how map features are drawn is maintained in a separate stylesheet file."_

What is restrictive - at least on Mapsforge maps - is the fixed labelling tags (seen also in [Tag](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/core/Tag.java)). But that is due to map file specification and cannot be changed without breaking compatibility.

**Comment by andreynovikov** [comment]
Examples of what I mean:

1. https://github.com/gravitystorm/openstreetmap-carto/blob/9f1b09feb4a8a57e50a8552e0d1fd3c5e7bd6a8c/placenames.mss#L67
2. https://github.com/gravitystorm/openstreetmap-carto/blob/9f1b09feb4a8a57e50a8552e0d1fd3c5e7bd6a8c/placenames.mss#L132
3. https://github.com/tangrams/simple-demo/blob/master/scene.yaml#L57
4. https://mapzen.com/blog/targeted-editing-transit-colours/
5. https://wiki.openstreetmap.org/wiki/Key:ref:colour
6. http://sinclarius.com/sfbus/

So, provided definition is wrong.

**Comment by devemux86** [comment]
Mapzen definition is wrong, where? Still do not understand the issue.
Those links don't show actual vector data, i.e. CartoCSS map stylesheets for rendering the data.
Or mean just better theme rules, e.g. using also inequality in comparisons?

BTW see also https://github.com/mapsforge/mapsforge/pull/1006.
