### ISSUE TITLE
Label priority based on an OSM tag value e.g. city population

### ISSUE THREAD

**Issue by TomasJohansson** [mapsforge/vtm#772]
If you want to display a country/state/cities map with little details (e.g. zoomed out) then you normally would prefer to display labels for big cities rather than small cities.
For example, I have created a map showing some cities in Florida, and when zoomed out it should show big cities such as Miami and Tampa, but instead it showed e.g. Homestead and Fort Pierce.
Also when zooming in around Miami, it instead showed the smaller cities Coral Gables and Miami Beach.
See the first two attached pictures.
![florida_cities_without_priority_1](https://user-images.githubusercontent.com/1504507/84671037-2a827700-af27-11ea-997f-af4a97ff3c3b.png)
![florida_cities_without_priority_2](https://user-images.githubusercontent.com/1504507/84671044-2e15fe00-af27-11ea-8e99-691a3145d887.png)

I tried to add a support for a "priority-key"
(similar to how to use the "textKey", the value of the attribute "k" in XmlThemeBuilder)
and then could achieve the more desirable result as illustrated in the last two attached pictures.
![florida_cities_with_priority_3](https://user-images.githubusercontent.com/1504507/84671144-4b4acc80-af27-11ea-92f1-01b05ad804e6.png)
![florida_cities_with_priority_4](https://user-images.githubusercontent.com/1504507/84671152-4e45bd00-af27-11ea-899f-4ca61069f316.png)

I can mention that the OSM file I was using was not retrieved from open street map, but I have used data from shapefiles at "naturalearthdata"
https://www.naturalearthdata.com

Then I generated an osm file (to use with osmosis to generate mapsforge file) from the shapefile, and it had this kind of tags:
```
<node ...
<tag k="name" v="Miami" />
<tag k="place" v="city" />
<tag k="population" v="5585000" />

<node ... 
<tag k="name" v="Coral Gables" />
<tag k="place" v="city" />
<tag k="population" v="150000" />
  
<node ... 
<tag k="name" v="Miami Beach" />
<tag k="place" v="city" />
<tag k="population" v="407750" />
```

And in the render file I used a "priority-key" value as below:
```
<caption k="name" priority-key="population" ...
```

@devemux86 can probably implement this feature much better than I have done, but if you want I can submit a PR.
Unless you for some reason do not even want to support this feature?

**Comment by devemux86** [comment]
Render themes already have a [priority tag](https://github.com/mapsforge/vtm/blob/master/docs/Rendertheme.md#priorities) which can be used for such categories.

OpenStreetMap has the [place key](https://wiki.openstreetmap.org/wiki/Key:place) to organize locations more nicely (see [theme](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/vtm/default.xml#L1275)).

Since priorities already exist in themes, the solution is to create properly the map.
Preprocess map elements and tag them based on population, if want such groups.

Also please such discussions should be done in the [forum](https://groups.google.com/group/mapsforge-dev).
