### ISSUE TITLE
Make vtm / vtm-android dependencies.

### ISSUE THREAD

**Issue by deviousgeek** [mapsforge/vtm#96]
I currently use the existing VTM library, and all I need to do is include them as dependencies ie:

`compile 'org.oscim:vtm:0.6.0-SNAPSHOT'`
`compile 'org.oscim:vtm-android:0.6.0-SNAPSHOT@aar'`

Any way I can achieve the same effect with this? Would _love_ to use an updated version of VTM. :)

:+1:

**Comment by devemux86** [comment]
Latest VTM can be used in two ways:
- Clone repository locally, run `gradle install` to you local `.m2` Maven repository and add `mavenLocal()` in your application's repositories.
- Or easier use JitPack as described in our [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#jitpack).

BTW we provide `vtm-android` as regular `jar`, because it does not need any Android resources.

For question please use our forum:
https://groups.google.com/group/mapsforge-dev
